### PR TITLE
New interp1d

### PR DESCRIPTION
**Pull request by al-jshen**
Replaces `torchinterp1d` with a new `interp1d` function in `spender/util.py`

The main motivation is that `torchinterp1d` seems to have some issues with backprop (at least on my machine, also see https://github.com/aliutkus/torchinterp1d/issues/16 and https://github.com/aliutkus/torchinterp1d/issues/17).

The new implementation also clamps at the edges instead of extrapolating.

### CODE REVIEW

**Comment by al-jshen** [comment]
This is unfortunately **extremely** slow compared to `torchinterp1d` (~100x slower on the forward pass according to pytest-benchmark) and I am not too sure why. I have everything running with @torch.jit.script and I've followed [this PyTorch guide](https://pytorch.org/tutorials/advanced/torch-script-parallelism.html) to parallelize the inner loop.

**Comment by pmelchior** [comment]
Is it slow for single spectra or batches of spectra?

**Comment by al-jshen** [comment]
Both.

**Comment by Ashkan13776** [comment]
Hi @al-jshen. How can I make this faster? Thanks!

**Pull request closed without merging**
