### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by EiffL**
Add missing dependency and automated install of interp1d

### CODE REVIEW

**Comment by pmelchior** [comment]
Thanks for your PR. We [used to have](https://github.com/pmelchior/spender/commit/d05a73d127ff2dfd38b74379b0aba72e8ffe1cf3) torchinterp1d listed with its git repo location, and this caused some trouble. I vaguely remember pypi was acting up with this config. The only difference I see  is that you provide the `egg` in the URL. Is that the magic trick to make it work?

**Comment by EiffL** [comment]
Ah, good point, I haven't tested what happens on pypi with this.... let me try to push my fork to test pypi and see what happens there

**Comment by EiffL** [comment]
annnnd... yeah, you are right :-( 
```
INFO     Response from https://test.pypi.org/legacy/:                                                  
         400 Invalid value for requires_dist. Error: Can't have direct dependency: 'torchinterp1d@     
         git+https://github.com/aliutkus/torchinterp1d.git#egg=torchinterp1d'                          
```

And ChatGPT does not believe there is a way to solve this that does not involve pushing torchinterp1d to pypi.

So.... maybe I'll just edit my PR to only add `nflows` and leave the rest as it is...

**Comment by pmelchior** [comment]
It's not that I haven't tried the pypi route with the maintainer: https://github.com/aliutkus/torchinterp1d/issues/18
Maybe you can raise it there again.

**Pull request closed without merging**
